### ISSUE TITLE
Edge segments with bendpoints not considered while finding average edge length

### ISSUE THREAD

**Issue by MobiZaman** [iVis-at-Bilkent/cytoscape.js-layvo#6]
The code for finding average edge length takes the straight line distance between the source and target of an edge. This is not valid when the edge has bendpoints and is composed of multiple edge segments.

**Comment by ugurdogrusoz** [comment]
@canbax Let's please add a parameter if needed to consider bend points in calculations of metrics involving edges. Particularly we at least need this for orthogonal edges (edges with horizontal and vertical line segments only). Notice that edge ends might have connection points / ports different from clipping points going into a node's center.

**Comment by ugurdogrusoz** [comment]
@MobiZaman Please verify

**Comment by MobiZaman** [comment]
@canbax I think there is a bug in the function getTotalEdgeLength() on line 279 of layout-evaluation.js? You are already updating the total edge length in the previous if else condition, so it is not supposed to be updated again at line 279.
